website/views/admin.py
from flask import (
    Blueprint,
    render_template,
    request,
    session,
    jsonify,
)
from website.utils import has_role
import pandas as pd
import website.db as DB


admin = Blueprint('admin', __name__)


@admin.route("/users", methods=("GET", "POST"))
def users():
    if has_role('triage'):
        if request.method == "GET":

            users = DB.get_users_as_dict()
            data = pd.DataFrame(users)
            data['registration_date'] = data['registration_date'].astype('datetime64[ns]')
            data['last_connection'] = data['last_connection'].astype('datetime64[ns]')
            data['days_since_last_connection'] = pd.to_datetime('now', utc=False) - data['last_connection']

            # Remove hashed mdp, useless in displayed table:
            data = data.drop('mdp', axis=1)

            # Render table:
            # Define value and text of the dropdown:
            role_choices = (("read", "read"),
                            ("write", "write"),
                            ("maintain", "maintain"),
                            ("triage", "triage"),
                            ("admin", "admin"))
            col2htmltitle = {'id': 'ID',
                             'nom': 'Nom',
                             'prenom': 'Prénom',
                             'email': 'Email',
                             'role': 'Rôle',
                             'registration_date': 'Création',
                             'last_connection': 'Dernière connection',
                             'days_since_last_connection': 'Delta',
                             }
            column_names = [col2htmltitle[v] for v in data.columns.values]

            return render_template("admin_users.html",
                                   column_names=column_names,
                                   rows=data.to_dict('records'),
                                   link_column="role",
                                   choices=role_choices,
                                   )

        elif request.method == "POST":
            # Update user role
            userId = request.json['userId']
            new_role = request.json['new_role']
            this_user = DB.get_user_by_id_as_dict(userId)

            if new_role == 'admin' and session['role'] == 'triage':
                success = False
                msg = "Seuls les 'admin' peuvent accorder ce rôle à un nouvel utilisateur"
            elif new_role in ['read', 'write', 'maintain', 'triage', 'admin']:
                try:
                    DB.update_user_role(this_user, new_role)
                    success = DB.get_user_by_id_as_dict(userId)['role'] == new_role
                    msg = "Rôle mis à jour"
                except Exception as e:
                    success = False
                    msg = str(e)
            #
            return jsonify({
                "status": success,
                "msg": msg,
            })

    else:
        msg = "Vous n'avez pas les droits d'accés à cette page d'administration"
        return render_template("error.html", msg=msg)

website/views/article.py
from flask import (
    Blueprint,
    render_template,
    g,
    url_for,
    redirect,
    request,
    session,
    flash,
)
from website.utils import (
    fix_url_for_miniature,
    delete_miniatures,
    has_role,
)
import website.db as DB
from website.images import ImageManager


article = Blueprint('article', __name__)


@article.url_value_preprocessor
def get_post_id(endpoint, values):
    post_id = values.pop('post_id')
    g.post_id = post_id
    print("post_id:", post_id)


@article.route("/")
def display():
    post = DB.get_post_as_dict(g.post_id)

    if post:
        post = fix_url_for_miniature(post)

        is_loggedin_the_author = post['created_by'] == DB.get_user_by_email_as_dict(session.get("username", False))['id'] if session.get("username", False) else False

        can_modify = has_role('maintain') or is_loggedin_the_author
        return render_template("article.html",
                               post=post,
                               can_modify=can_modify,
                               can_suppr=can_modify,
                               active='blog')
    else:
        return render_template('error.html',
                               active='blog',
                               msg="L'article '%i' est introuvable" % g.post_id), 404


@article.route("/edit", methods=("GET", "POST"))
def edit():
    if has_role('write'):
        post = DB.get_post_as_dict(g.post_id)
        if request.method == "GET":
            return render_template("article_edit.html", post=post)
        elif request.method == "POST":
            title = request.form["title"]
            content = request.form["content"]
            miniature = request.files["miniature"]
            if not title:
                flash("Un titre est requis !")
            else:
                if miniature.filename:
                    f = ImageManager(miniature)  # Le fichier est telecharge automatiquement
                    filename = f.name_in_store  # pour l'enregistrement en base
                    delete_miniatures(post)  # Supprime l'ancienne image
                else:
                    filename = post['miniature']
                DB.update_post(title,
                               content,
                               g.post_id,
                               DB.get_user_by_email_as_dict(session.get("username"))['id'],
                               filename)
                return redirect(url_for(".display", post_id=g.post_id))
    else:
        return render_template("error.html", msg="Vous n'êtes pas autorisé.e à éditer cet article")


@article.route("/delete", methods=("GET", "POST"))
def delete():
    if session.get("id", False):
        post = DB.get_post_as_dict(g.post_id)
        if has_role('maintain') or session['id'] == post['created_by']:
            # Supprime les images du post:
            delete_miniatures(post)

            # Puis supprime le post de la base de donnees:
            DB.delete_post(g.post_id)

            flash('Article "{}" supprimé avec succès !'.format(post["title"]))
            return redirect(url_for("blog.display"))

        else:
            return render_template("error.html", msg="Vous n'êtes pas autorisé.e à supprimer cet article")
    else:
        return render_template("error.html", msg="Vous devez être connecté.e pour supprimer un article")


@article.route("/delete_image", methods=("GET", "POST"))
def delete_image():
    if session.get("id", False):
        post = DB.get_post_as_dict(g.post_id)
        if has_role('maintain') or session['id'] == post['created_by']:
            # Supprime uniquement les images du post:
            post = delete_miniatures(post)

            # Maj de la base:
            DB.update_post(post['title'],
                           post['content'],
                           g.post_id,
                           DB.get_user_by_email_as_dict(session.get("username"))['id'],
                           post['miniature'])

            flash('Images de "{}" supprimée avec succès !'.format(post["title"]))
        else:
            flash("Vous n'êtes pas autorisé.e à supprimer cette image")

        return redirect(url_for(".display", post_id=g.post_id))

    else:
        return render_template("error.html", msg="Vous devez être connecté.e pour supprimer cette image")

website/views/blog.py
from flask import (
    Blueprint,
    render_template,
    url_for,
    redirect,
    request,
    session,
    flash,
)
from website.utils import (
    fix_url_for_miniature,
    has_role,
)
import website.db as DB
from website.images import ImageManager


blog = Blueprint('blog', __name__)


@blog.route("/")
def display():
    posts = DB.get_posts_as_dict()
    posts_to_publish = []
    if len(posts) > 0:
        for p in posts:
            p = fix_url_for_miniature(p)
            posts_to_publish.append(p)

        # Trie les articles pour que le plus recent soit en premier:
        posts_to_publish.sort(key=lambda k: k.get("created"), reverse=True)

    #
    return render_template(
        "blog.html", posts=posts_to_publish, can_write=has_role('write'), active="blog"
    )


@blog.route("/create", methods=("GET", "POST"))
def create():
    if has_role('write'):
        if request.method == "POST":
            account = DB.get_user_by_email_as_dict(session.get("username"))
            title = request.form["title"]
            content = request.form["content"]
            miniature = request.files["miniature"]
            # annexe = request.files['annexe']
            if not title:
                flash("Un titre est requis !")
            else:
                if miniature.filename:
                    f = ImageManager(miniature)  # Le fichier est telecharge automatiquement
                    filename = f.name_in_store
                else:
                    filename = ""
                DB.insert_post(title, content, filename, account['id'])
                return redirect(url_for(".display"))
        return render_template("article_create.html")
    else:
        flash("Vous n'êtes pas autorisé à écrire des articles")
        return redirect(url_for("profile.login"))

website/views/user.py
from flask import (
    Blueprint,
    render_template,
    url_for,
    redirect,
    request,
    session,
    flash,
    jsonify,
    current_app,
)
from werkzeug.security import check_password_hash
import re
import website.db as DB
from website.utils import has_role


user = Blueprint('user', __name__)


@user.route("/", methods=["GET"])
def account():
    if session.get("username", False):
        user_data = DB.get_user_by_email_as_dict(session.get("username"))
        return render_template("user.html", account=user_data)
    else:
        return redirect(url_for("user.register"))


@user.route("/register", methods=["GET", "POST"])
def register():
    if (
        request.method == "POST"
        and "email" in request.form
        and "nom" in request.form
        and "prenom" in request.form
        and "mdp" in request.form
    ):
        email = request.form["email"]
        nom = request.form["nom"]
        prenom = request.form["prenom"]
        mdp = request.form["mdp"]
        if DB.get_user_by_email_as_dict(email):
            flash("Cet email est déjà associé à un compte dans notre base. Utiliser un autre email.")
        elif not re.match(r"[^@]+@[^@]+\.[^@]+", email):
            flash("Email invalide")
        elif not nom or not prenom or not mdp or not email:
            flash("Remplir le formulaire !")
        else:
            # Si le compte n'existe pas:
            DB.insert_user(nom, prenom, email, mdp, role=current_app.config['DEFAULT_ROLE'])
            user_data = DB.get_user_by_email_as_dict(email)  # get new account data
            flash("Compte enregistré avec succés")

            # creer une session
            session["loggedin"] = True
            session["id"] = user_data["id"]
            session["name"] = "%s, %s" % (user_data["nom"], user_data["prenom"])
            session["username"] = user_data["email"]
            session["role"] = user_data["role"]

            return redirect(url_for("main.home"))
    elif request.method == "POST":
        # si le formulaire est vide
        flash("Remplir tous les champs !")

    # else return the registration page:
    return render_template("user_register.html")


@user.route("/login", methods=["GET", "POST"])
def login():
    if request.method == "POST" and "email" in request.form and "mdp" in request.form:
        email, mdp = request.form["email"], request.form["mdp"]

        # Cherche si le compte existe:
        user_data = DB.get_user_by_email_as_dict(email)
        if user_data:
            if check_password_hash(user_data["mdp"], mdp) == True:  # Mot de passe OK
                # Creation d'une session:
                session["loggedin"] = True
                session["id"] = user_data["id"]
                session["name"] = "%s %s" % (user_data["prenom"], user_data["nom"])
                session["username"] = user_data["email"]
                session["role"] = user_data["role"]
                DB.update_last_login(email)
                flash('Vous vous êtes connecté(e) avec succés')
                return redirect(url_for("main.home"))
            else:
                # Mot de passe incorrect:
                flash("Mot de passe INCORRECT")
        else:
            # Compte n'existe pas:
            flash("Cet email n'est pas dans notre base: '%s'" % email)
    return render_template("user_login.html")


@user.route("/logout")
def logout():
    # supprimer les données de sessions
    session.pop("loggedin", None)
    session.pop("id", None)
    session.pop("name", None)
    session.pop("username", None)
    session.pop("role", None)
    session.pop("lr", None)
    session.clear()
    return redirect(url_for("user.login"))


@user.route("/delete", methods=["POST"])
def delete():
    if session.get("username", False) and request.method == "POST":
        if 'email' in request.form:
            # Request coming from the user account page:
            email = request.form["email"]
            if has_role('admin') or email == session.get("username"):
                DB.delete_user(email)
                logout()
                flash('Compte "{}" supprimé avec succès !'.format(email))
                return redirect(url_for("main.home"))
            else:
                return render_template("error.html", msg="Impossible de supprimer ce compte ('%s')" % email)

        elif 'userId' in request.json:
            # Request coming from the admin users page:
            if has_role('admin'):
                userId = request.json['userId']
                try:
                    user_data = DB.get_user_by_id_as_dict(userId)
                    DB.delete_user(user_data['email'])
                    success = True
                    msg = "Compte id=%s (%s) supprimé avec succés !" % (userId, user_data['email'])
                except Exception as e:
                    success = False
                    msg = str(e)
                return jsonify({
                        "status": success,
                        "msg": msg,
                        "userId": userId,
                    })
            else:
                msg = "Vous n'avez pas assez de privilèges pour supprimer le compte d'un utilisateur"
                return render_template("error.html", msg=msg)



@user.route("/edit", methods=["GET", "POST"])
def edit():
    if session.get("username", False) and request.method == "POST":
        previous_email = session['username']
        if (
            "email" in request.form
            and "nom" in request.form
            and "prenom" in request.form
        ):
            email = request.form["email"]
            nom = request.form["nom"]
            prenom = request.form["prenom"]
            user_data = DB.get_user_by_email_as_dict(email)
            if user_data:
                if not re.match(r"[^@]+@[^@]+\.[^@]+", email):
                    flash("Email invalide")
                elif email != previous_email:
                    # Check if new email is not used by another user:
                    if DB.get_user_by_email_as_dict(email) is not None:
                        flash("Cet email est déjà utilisé par un(e) autre utilisateur(trice)")
                        user_data = DB.get_user_by_email_as_dict(previous_email)
                        pass

                else:
                    DB.update_user(previous_email, nom, prenom, email)
                    # Update session with new data:
                    user_data = DB.get_user_by_email_as_dict(email)
                    session["id"] = user_data["id"]
                    session["name"] = "%s, %s" % (user_data["nom"], user_data["prenom"])
                    session["username"] = user_data["email"]
                    session["role"] = user_data["role"]
                    session["email"] = user_data["email"]
                    flash("Informations mises à jour")

    return render_template("user.html", account=user_data)

website/templates/admin_users.html
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Low-Tech Lab Brest: Gestion des comptes utilisateur</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/style.css')}} ">
    <link rel="stylesheet" href="{{ url_for('static',filename='styles/user.css')}} ">
</head>

<body>
    <header>
    {% include "partials/_navbar.html" %}
    </header>

    <div class="content">
        <form id="users_table">
            <table id="Mapped table" class="users">
                <caption>Liste des utilisateurs</caption>
                <thead>
                    <tr>
                        {% for col in column_names %}
                        {% if col != 'Delta' %}
                        <th>{{col}}</th>
                        {% endif %}
                        {% endfor %}
                        {% if has_role('admin') %}
                        <th>Danger zone</th>
                        {% endif %}
                    </tr>
                </thead>
                <tbody>
                    {% for row in rows %}
                    <tr id="row-user-{{row['id']}}">
                        {% for key, val in row.items() %}
                        {% if key == link_column %}
                        <td>
                            <select class="dropbtn" data-user-id="{{ row['id'] }}">
                            {% for choice in choices %}
                                <option value={{ choice[0] }}
                                {% if choice[0] == val %} selected {% endif %}>
                                {{ choice[1] }}
                                </option>
                            {% endfor %}
                            </select>
                        </td>
                        {% elif key == 'registration_date' %}
                        <td>
                            {{ val|format_datetime('full') }}
                        </td>
                        {% elif key == 'last_connection' %}
                        <td>
                            Il y a {{ row['days_since_last_connection']|format_timedelta('day') }}
                            ({{ val|format_datetime('short') }})
                        </td>
                        {% elif key != 'days_since_last_connection' %}
                        <td>
                            {{ val }}
                        </td>
                        {% endif %}
                        {% endfor %}
                        {% if has_role('admin') %}
                        <td>
                            <input type="button" value="Supprimer" data-user-id="{{ row['id'] }}" class="suppress">
                        </td>
                        {% endif %}
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </form>

        <div class="legend">
        <h3>Détails des privilèges pour les rôles:</h3>
        <p>Rq: Les privilèges se cumulent</p>
        <ol>
            <li><b>Read</b>: Peut lire tout le contenu du site</li>
            <li><b>Write</b>: Peut écrire un article de blog puis le modifier ou le supprimer</li>
            <li><b>Maintain</b>: Peut modifier ou supprimer n'importe quel article</li>
            <li><b>Triage</b>: Peut voir la liste des utilisateurs et modifier le rôle de n'importe lequel</li>
            <li><b>Admin</b>: Peut supprimer un utilisateur</li>
        </ol>
        </div>
    </div>

    <footer>
    {% include "partials/_footer.html" %}
    </footer>


    <script>
        let els_chg = document.getElementsByClassName("dropbtn");
        Array.from(els_chg).forEach(function (element) {
            element.addEventListener("change", function() {
                let data = {
                    'userId': this.dataset.userId,
                    'new_role': this.value,
                };
                let url = {{ url_for("admin.users")|tojson }};
                fetch(url, {
                    method: "POST",
                    body: JSON.stringify(data),
                    headers: {
                        "Content-type": "application/json; charset=UTF-8"
                    }
                })
                .then(response => response.json())
                .then(data => {
                    console.log(data);
                    alert(data['msg']);
                })
                {#console.log(text + " = " + value + " for user id: " + user_id);#}
            });
        });

        {% if has_role('admin') %}

        let els_del = document.getElementsByClassName("suppress");
        Array.from(els_del).forEach(function (element) {
            element.addEventListener("click", function() {
                let data = {
                    'userId': this.dataset.userId,
                };
                if (confirm("Etes-vous sûr(e) de vouloir supprimer ce compte ?") == true) {
                    let url = {{ url_for("user.delete")|tojson }};
                    fetch(url, {
                        method: "POST",
                        body: JSON.stringify(data),
                        headers: {
                            "Content-type": "application/json; charset=UTF-8"
                        }
                    })
                        .then(response => response.json())
                        .then(data => {
                            alert(data['msg']);
                            if (data['status'] == true) {
                                document.getElementById("row-user-" + data['userId']).remove();
                            }
                            ;
                        })
                } else {
                    console.log("Operation annullee");
                }
                {#console.log(text + " = " + value + " for user id: " + user_id);#}
            });
        });

        {% endif %}

    </script>

</body>
</html>

website/templates/article.html
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Low-Tech Lab Brest: {{ post['title'] }}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/style.css')}} ">
    <link rel="stylesheet" href="{{ url_for('static',filename='styles/post.css')}} ">
    <script type="module" src="https://cdn.jsdelivr.net/gh/zerodevx/zero-md@2/dist/zero-md.min.js"></script>
</head>

<body>
    <header>
    {% include "partials/_navbar.html" %}
    </header>

    <div class="blog">
        <div class="article">
            <div class="article-header">
                <div class="article-stamps">
                    <p class="article-author">Par <span style="font-weight: bold">{{ post['author']['prenom'] }} {{ post['author']['nom'] }}</span> </p>
                    <p class="article-date">{{ post['created']|format_datetime('full') }}</p>
                    {% if post['created']|format_datetime('full') != post['modified']|format_datetime('full') %}
                    <p class="article-update">Mis à jour le {{ post['modified']|format_datetime('full') }}
                        {% if post['modifier']['email'] != post['author']['email'] %} par {{ post['modifier']['prenom'] }} {{ post['modifier']['nom'] }}{% endif %}
                    </p>
                    {% endif %}
                </div>
                <div class="article-edit">
                    {% if can_modify %}
                    <a  class="btn" href="{{ url_for('article.edit', post_id=post['id']) }}">Modifier</a>
                    {% endif %}
                    {% if can_suppr %}
                    <div>
                    <form action="{{ url_for('article.delete', post_id=post['id']) }}" method="POST">
                        <input type="submit" value="Supprimer"
                                class="btn btn-danger btn-sm"
                                onclick="return confirm('Etes-vous sûr de vouloir supprimer cet article ?')">
                    </form>
                    </div>
                    {% endif %}
                </div>
                {% if post['miniature'] %}
                <img src="{{ post['miniature'] }}" class="img-post">
                {% endif %}
            </div>
            <div class="article-body">
                <h2 class="titre">{% block title %} {{ post['title'] }} {% endblock %}</h2>
                <p class="paragraphe">
                    <zero-md>
                      <script type="text/markdown" data-dedent>
                            {{ post['content'] }}
                      </script>
                    </zero-md>
                </p>
            </div>
        </div>
    </div>

    <footer>
    {% include "partials/_footer.html" %}
    </footer>
</body>
</html>

website/templates/article_edit.html
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Low-Tech Lab Brest: Edition {{ post['title'] }}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/style.css')}} ">
    <link rel="stylesheet" href="{{ url_for('static',filename='styles/post.css')}} ">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.css">
    <script src="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.js"></script>
</head>

<body>
    <header>
    {% include "partials/_navbar.html" %}
    </header>

    <div class="create">
        <h1>{% block title %} Edit "{{ post['title'] }}" {% endblock %}</h1>
        <form method="post" enctype="multipart/form-data">
            <div class="form-group">
                <label for="title">Titre:</label>
                <input type="text" name="title" placeholder="Post title"
                    class="form-control" size="50"
                    value="{{ request.form['title'] or post['title'] }}">
            </div>
            <div class="form-group">
                <label for="miniature">Mettre à jour la miniature: </label>
                <input type="file" id="miniature" name="miniature" accept=".jpg, .jpeg, .png"
                value="{{ request.form['miniature'] }}">
            </div>
            <div class="form-group">
                <textarea name="content" placeholder="Post content" rows="25" cols="150"
                        class="form-control">{{ request.form['content'] or post['content'] }}</textarea>
            </div>
            <div class="form-group">
                <button class="btn" type="submit">Mettre à jour</button>
            </div>
        </form>
        <form action="{{ url_for('article.delete_image', post_id=post['id']) }}" method="POST">
            <div class="form-group">
            <button class="btn" type="submit" onclick="return confirm('Etes-vous sûr de vouloir supprimer l''image de cet article ?')">Supprimer l'image uniquement</button>
            </div>
        </form>
        <form action="{{ url_for('article.delete', post_id=post['id']) }}" method="POST">
            <div class="form-group">
            <button class="btn" type="submit" onclick="return confirm('Etes-vous sûr de vouloir supprimer cet article ?')">Supprimer l'article</button>
            </div>
        </form>
    </div>

    <footer>
    {% include "partials/_footer.html" %}
    </footer>

    <script>
        var simplemde = new SimpleMDE();
    </script>
</body>

</html>

website/templates/blog.html
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Low-Tech Lab Brest: Articles</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/style.css')}} ">
    <link rel="stylesheet" href="{{ url_for('static',filename='styles/post.css')}} ">
</head>

<body>
    <header>
    {% include "partials/_navbar.html" %}
    </header>

    <div class="blog">
        <div>
        {% if can_write %}
        <a class="btn" href="create">Ecrire un article</a>
        {% endif %}
        </div>

        <div class="articles">
            {% for post in posts %}
            <div class="article-sample">
                <a href="{{ url_for('article.display', post_id=post['id']) }}">
                    {% if post['miniature'] %}
                    <div>
                        <img src={{ post['miniature'] }} class="img-post">
                    </div>
                    {% else %}
                    <div>
                        <img src="{{url_for('static', filename='ressource/logo_remov.png')}}" class="img-post">
                    </div>
                    {% endif %}
                    <div>
                        <h2 class="titre">{{ post['title'] }}</h2>
                    </div>
                    <div>
                        <span class="badge badge-primary">{{ post['created']|format_datetime('medium') }}</span>
                    </div>
                </a>
            </div>
            {% endfor %}
        </div>
    </div>

    <footer>
    {% include "partials/_footer.html" %}
    </footer>
</body>

</html>

website/templates/test.html
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Low-Tech Lab Brest: Test</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/style.css')}} ">
</head>

<body>
    <header>
    {% include "partials/_navbar.html" %}
    </header>

    <div class="content">
    </div>

    <footer>
    {% include "partials/_footer.html" %}
    </footer>
</body>
</html>

website/templates/user.html
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Low-Tech Lab Brest: Compte utilisateur</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/style.css')}} ">
    <link rel="stylesheet" href="{{ url_for('static',filename='styles/user.css')}} ">
</head>

<body>
    <header>
    {% include "partials/_navbar.html" %}
    </header>

    <section class="formulaire">

        <form action="{{ url_for('user.edit') }}" method="POST" class="account">
            <h1>Votre compte:</h1>
    
            <div class="inputs">
                <input type="email" name="email" placeholder="Email" id="email" required value="{{account['email']}}">
                <input type="text" name="nom" placeholder="Nom" id="nom" required value="{{account['nom']}}">
                <input type="text" name="prenom" placeholder="Prenom" id="prenom" required value="{{account['prenom']}}">
                <input class="btn" type="submit" value="Modifier">
            </div>
            <br>
            <p>Informations internes:
            <ul>
                <li>Date de création du compte: {{ account['registration_date'][0:16] }}</li>
                <li>Dernière connection: {{ account['last_connection'][0:16] }}</li>
                <li>Type de compte: "{{ account['role'] }}"</li>
            </ul>
            </p>
        </form>
        <form action="{{ url_for('user.delete') }}" method="POST" class="account">
            <h1>Zone de danger</h1>
            <input type="email" name="email" value="{{account['email']}}" hidden>
            <input type="submit" value="Supprimer son compte" class="btn btn-danger btn-sm"
                onclick="return confirm('Etes-vous sûr(e) de vouloir supprimer votre compte ?')">
        </form>
    </section>

    <footer>
    {% include "partials/_footer.html" %}
    </footer>

</body>
</html>