website/views/admin.py
from flask import (
    Blueprint,
    render_template,
    request,
    session,
    jsonify,
)
from website.utils import has_role
import pandas as pd
import website.db as DB


admin = Blueprint('admin', __name__)


@admin.route("/users", methods=("GET", "POST"))
def users():
    if has_role('triage'):
        if request.method == "GET":

            users = DB.get_users_as_dict()
            data = pd.DataFrame(users)
            data['registration_date'] = data['registration_date'].astype('datetime64[ns]')
            data['last_connection'] = data['last_connection'].astype('datetime64[ns]')
            data['days_since_last_connection'] = pd.to_datetime('now', utc=False) - data['last_connection']

            # Remove hashed mdp, useless in displayed table:
            data = data.drop('mdp', axis=1)

            # Render table:
            # Define value and text of the dropdown:
            role_choices = (("read", "read"),
                            ("write", "write"),
                            ("maintain", "maintain"),
                            ("triage", "triage"),
                            ("admin", "admin"))
            col2htmltitle = {'id': 'ID',
                             'nom': 'Nom',
                             'prenom': 'Prénom',
                             'email': 'Email',
                             'role': 'Rôle',
                             'registration_date': 'Création',
                             'last_connection': 'Dernière connection',
                             'days_since_last_connection': 'Delta',
                             }
            column_names = [col2htmltitle[v] for v in data.columns.values]

            return render_template("admin_users.html",
                                   column_names=column_names,
                                   rows=data.to_dict('records'),
                                   link_column="role",
                                   choices=role_choices,
                                   )

        elif request.method == "POST":
            # Update user role
            userId = request.json['userId']
            new_role = request.json['new_role']
            this_user = DB.get_user_by_id_as_dict(userId)

            if new_role == 'admin' and session['role'] == 'triage':
                success = False
                msg = "Seuls les 'admin' peuvent accorder ce rôle à un nouvel utilisateur"
            elif new_role in ['read', 'write', 'maintain', 'triage', 'admin']:
                try:
                    DB.update_user_role(this_user, new_role)
                    success = DB.get_user_by_id_as_dict(userId)['role'] == new_role
                    msg = "Rôle mis à jour"
                except Exception as e:
                    success = False
                    msg = str(e)
            #
            return jsonify({
                "status": success,
                "msg": msg,
            })

    else:
        msg = "Vous n'avez pas les droits d'accés à cette page d'administration"
        return render_template("error.html", msg=msg)

website/views/api.py
from flask import (
    Blueprint,
    render_template,
    request,
    session,
    jsonify,
    abort,
    make_response,
)

import plotly
import plotly.express as px
import json
import dateutil
from dateutil import tz
from typing import Union
from website.utils import lr_state, datadict2csv
from website.monitors import read_save_data
import website.db as DB

api = Blueprint('api', __name__)


class InvalidAPIUsage(Exception):
    status_code = 400

    def __init__(self, message, status_code=None, payload=None):
        super().__init__()
        self.message = message
        if status_code is not None:
            self.status_code = status_code
        self.payload = payload

    def to_dict(self):
        rv = dict(self.payload or ())
        rv['message'] = self.message
        return rv


@api.errorhandler(InvalidAPIUsage)
def invalid_api_usage(e):
    return jsonify(e.to_dict()), e.status_code


@api.route("/img_res", methods=['GET'])
def image_quality():
    """Use this route to read or change the 'lr' session parameter controlling Image quality"""
    lr = request.args.get("lr", type=lambda x: x.lower() in ["1", "true"])

    if "set_lr" in request.args:
        # Apply new state to session:
        session["lr"] = lr

    return jsonify({"lr": lr_state()})


@api.route("/sensors", methods=['GET'])
def read_sensors():
    # /sensors
    # /sensors?n=1
    # /sensors?n=1000&q=pourcentage_BAT
    # /sensors?n=1000&q=pourcentage_BAT,luminosite
    # /sensors?n=1000&q=pourcentage_BAT,luminosite&format=csv

    # Lit et valide les arguments eventuels de la requete:

    n = request.args.get("n", default=DB.get_sensor_tablelen())
    n = valid_n_records(n)

    fields = request.args.get("q", default='tous')
    fields = valid_sensors_list(fields, errors='raise')
    fields = fields + ['record'] if 'record' not in fields else fields

    # Recupere les donnees:
    data = DB.get_sensors_data_as_dict(fields=fields, n=n)
    # print(data)

    # Possibly change data format:
    format = valid_format(request.args.get("format", default='json'))

    if format == 'json':
        return jsonify({"data": data})
    elif format == 'csv':
        data = datadict2csv(data)
        output = make_response(data)
        output.headers["Content-type"] = "text/plain; charset=utf-8"
        return output


@api.route("/records_length", methods=['GET'])
def read_n():
    n1 = DB.get_sensor_tablelen()
    n2 = DB.get_server_tablelen()
    return jsonify({"data": {'sensors': n1, 'server': n2}})


@api.route("/sensors_list", methods=['GET'])
def list_sensors():
    data = DB.get_sensor_list()
    data = DB.get_server_var_list()
    return jsonify({"data": data})


@api.route("/server_list", methods=['GET'])
def list_server():
    data = DB.get_server_var_list()
    return jsonify({"data": data})


@api.route("/server", methods=['GET'])
def read_server():
    # /server
    # /server?n=1
    # /server?n=1000&q=cpu
    # /server?n=1000&q=cpu,mem&format=csv

    # Lit et valide les arguments eventuels de la requete:

    n = request.args.get("n", default=DB.get_server_tablelen())
    n = valid_n_records(n)

    fields = request.args.get("q", default='tous')
    fields = valid_server_data_list(fields, errors='raise')
    fields = fields + ['record'] if 'record' not in fields else fields

    # Recupere les donnees:
    data = DB.get_server_data_as_dict(fields=fields, n=n)
    # print(data)

    # Possibly change data format:
    format = valid_format(request.args.get("format", default='json'))

    if format == 'json':
        return jsonify({"data": data})
    elif format == 'csv':
        data = datadict2csv(data)
        output = make_response(data)
        output.headers["Content-type"] = "text/plain; charset=utf-8"
        return output


@api.route("/gauges", methods=['GET'])
def read_gauges():
    """A gauge is a unique value out of a timeseries"""
    # /gauges
    # /gauges?q=cpu
    # /gauges?q=cpu,pourcentage_BAT

    #
    fields_server = request.args.get("q", default='tous')
    fields_server = valid_server_data_list(fields_server, errors='ignore')
    data_server = {}
    if len(fields_server):
        data_server = DB.get_server_data_as_dict(fields=fields_server, n=1)
        # data_server['record_server'] = data_server['record']
        # data_server.pop('record')


    fields_sensors = request.args.get("q", default='tous')
    fields_sensors = valid_sensors_list(fields_sensors, errors='ignore')
    data_sensors = {}
    if len(fields_sensors):
        data_sensors = DB.get_sensors_data_as_dict(fields=fields_sensors, n=1)
        # data_sensors['record_sensors'] = data_sensors['record']
        # data_sensors.pop('record')

    data = {**data_server, **data_sensors}
    if 'id' in data:
        data.pop('id')
    if 'record' in data:
        data.pop('record')

    return jsonify({"data": data})


@api.route("/graphJSON")
def graphe():
    """Return a JSON for a plotly timeseries"""
    sensor_data = DB.get_sensors_data_as_dict()
    # server_data = DB.get_server_data_as_dict()

    # Plotly doesn't currently support timezones:
    sensor_data['record'] = [dateutil.parser.isoparse(d) for d in sensor_data['record']]
    sensor_data['record'] = [d.astimezone(tz=dateutil.tz.tzlocal()) for d in sensor_data['record']]

    #
    fig = px.line(sensor_data, x='record', y='pourcentage_BAT', width=1000,
                  labels={
                     "record": "Temps",
                     "pourcentage_BAT": "Pourcentage de charge",
                     },
                title="Historique de la batterie")
    graphJSON = json.dumps(fig, cls=plotly.utils.PlotlyJSONEncoder)

    return jsonify({"data": graphJSON})


def valid_sensors_list(fields: Union[str, list], errors='raise') -> list:
    """Retourne une liste de variables valides ou une erreur"""
    fields_valid = DB.get_sensor_list()
    if fields == 'all' or fields == 'tous':
        fields = fields_valid
    else:
        fields = fields.split(',')
    # print("fields=", fields)

    # Valide la liste des variables demandees:
    not_valid = []
    validated = []
    for f in fields:
        if f not in fields_valid:
            not_valid.append(f)
        else:
            validated.append(f)
    if len(not_valid) > 0 and errors=='raise':
        raise InvalidAPIUsage("Nom(s) de variable invalide(s): [%s]" % (",".join(not_valid)),
                              payload={'request': request.args,
                                       'variables_autorisees':  [v for v in ['tous'] + fields_valid]})
    return validated


def valid_server_data_list(fields: Union[str, list], errors='raise') -> list:
    """Retourne une liste de variables valides ou une erreur"""
    fields_valid = DB.get_server_var_list()
    if fields == 'all' or fields == 'tous':
        fields = fields_valid
    else:
        fields = fields.split(',')
    # print("fields=", fields)

    # Valide la liste des variables demandees:
    not_valid = []
    validated = []
    for f in fields:
        if f not in fields_valid:
            not_valid.append(f)
        else:
            validated.append(f)
    if len(not_valid) > 0 and errors == 'raise':
        raise InvalidAPIUsage("Nom(s) de variable invalide(s): [%s]" % (",".join(not_valid)),
                              payload={'request': request.args,
                                       'variables_autorisees':  [v for v in ['tous'] + fields_valid]})
    return validated


def valid_gauge_data_list(fields: Union[str, list], errors='raise') -> list:
    """Retourne une liste de variables valides ou une erreur"""
    fields_server = DB.get_server_var_list()
    fields_sensors = DB.get_sensor_list()
    fields_valid = fields_server + fields_sensors
    fields_valid = list(dict.fromkeys(fields_valid))  # Remove possible duplicate from the list
    fields_valid.sort()

    if fields == 'all' or fields == 'tous':
        fields = fields_valid
    else:
        fields = fields.split(',')

    not_valid = []
    validated = []
    for key in fields:
        if key in fields_server or key in fields_sensors:
            validated.append(key)
        else:
            not_valid.append(key)

    if len(not_valid) > 0 and errors == 'raise':
        raise InvalidAPIUsage("Nom(s) de variable invalide(s): [%s]" % (",".join(not_valid)),
                              payload={'request': request.args,
                                       'variables_autorisees':  [v for v in ['tous'] + fields_valid]})
    else:
        validated = list(dict.fromkeys(validated))  # Remove duplicate from the list
        validated.sort()
        return validated


def valid_n_records(n) -> int:
    if str(n).isdigit() and int(n) > 0:
        return int(n)
    else:
        raise InvalidAPIUsage("Le nombre d'enregistrements demandes 'n' doit etre un entier strictement positif",
                              payload={'request': request.args})


def valid_format(f: str) -> str:
    fields_valid = ['json', 'csv']
    if f in fields_valid:
        return str(f)
    else:
        raise InvalidAPIUsage("Format invalide",
                              payload={'request': request.args, 'format_autorises':  [v for v in fields_valid]})

website/views/blog.py
from flask import (
    Blueprint,
    render_template,
    url_for,
    redirect,
    request,
    session,
    flash,
)
from website.utils import (
    fix_url_for_miniature,
    has_role,
)
import website.db as DB
from website.images import ImageManager


blog = Blueprint('blog', __name__)


@blog.route("/")
def display():
    posts = DB.get_posts_as_dict()
    posts_to_publish = []
    if len(posts) > 0:
        for p in posts:
            p = fix_url_for_miniature(p)
            posts_to_publish.append(p)

        # Trie les articles pour que le plus recent soit en premier:
        posts_to_publish.sort(key=lambda k: k.get("created"), reverse=True)

    #
    return render_template(
        "blog.html", posts=posts_to_publish, can_write=has_role('write'), active="blog"
    )


@blog.route("/create", methods=("GET", "POST"))
def create():
    if has_role('write'):
        if request.method == "POST":
            account = DB.get_user_by_email_as_dict(session.get("username"))
            title = request.form["title"]
            content = request.form["content"]
            miniature = request.files["miniature"]
            # annexe = request.files['annexe']
            if not title:
                flash("Un titre est requis !")
            else:
                if miniature.filename:
                    f = ImageManager(miniature)  # Le fichier est telecharge automatiquement
                    filename = f.name_in_store
                else:
                    filename = ""
                DB.insert_post(title, content, filename, account['id'])
                return redirect(url_for(".display"))
        return render_template("article_create.html")
    else:
        flash("Vous n'êtes pas autorisé à écrire des articles")
        return redirect(url_for("profile.login"))

website/views/main.py
from flask import (
    Blueprint,
    render_template,
    request,
    session,
    jsonify,
)
from website.utils import lr_state


main = Blueprint('main', __name__)


@main.route("/")
def home():
    return render_template("index.html", active="home")


@main.route("/a_propos")
def a_propos():
    return render_template("a_propos.html", active="a_propos")

website/templates/partials/_footer.html
<div class="footer">
    <div class="plan_site">
        <h2>Plan du site</h2>
        <ul>
            <li><a href="{{ url_for('main.home') }}">Accueil</a></li>
            <li><a href="{{ url_for('blog.display') }}">Articles</a></li>
            <li><a href="#">Agenda</a></li>
            <li><a href="#">Projets</a></li>
            <li><a href="{{ url_for('main.a_propos') }}">C'est quoi le Low-Tech ?</a></li>
            <li><a href="{{ url_for('dashboard.display') }}">Serveur solaire</a></li>
        </ul>
    </div>

    <div class="coordonnes">
        <h2>Coordonnées</h2>
        <ul>
            <li>bonjour@lowtechlabbrest.org</li>
            <li><a target="_blank" href="https://www.openstreetmap.org/?mlat=48.41394&mlon=-4.46169#map=19/48.41394/-4.46169">13 rue Maupertuis, 29200 Brest</a></li>
        </ul>
    </div>

    <div class="sociaux">
        <h2>Réseaux sociaux</h2>
        <ul>
            <li> <a href="https://discord.gg/2MS25eYT">Discord</a></li>
            <li> <a href="https://www.instagram.com/low_tech_lab_brest/">Instagram</a></li>
            <li> <a href="https://www.linkedin.com/company/low-tech-lab-brest/?originalSubdomain=fr">LinkedIn</a></li>
            <li> <a href="https://www.facebook.com/lowtechlabbrest/">Facebook</a> </li>
        </ul>
    </div>

    <div class="users">
        <h2>Utilisateur</h2>
        <ul>
            {% if session['loggedin'] %}
              <li>{{ session['name'] }} - {{ session['role'] }}</li>
              <li><a href="{{ url_for('user.account') }}">Gérer son compte</a></li>
              <li><a href="{{ url_for('user.logout') }}">Se déconnecter</a></li>
            {% else %}
              <li><a href="{{ url_for('user.login') }}">Se connecter</a> ou <a href="{{ url_for('user.register') }}">Créer un compte</a></li>
            {% endif %}
            {% if has_role('triage') %}
            <li><a href="{{ url_for('admin.users') }}">Gestion des utilisateurs</a></li>
            {% endif %}
        </ul>
    </div>


    <div class="bottomright">
      <img id="battery-image" src="{{
        url_for('static', filename='ressource/low.png')
      }}" width="30" height="30">
    </div>

    {% if pourcent_battery_recupere is not none %}
    {% if pourcent_battery_recupere >= 80 %}
      <script>
        var batteryImg = document.getElementById("battery-image");
        batteryImg.src = "{{url_for('static',filename='ressource/high.png')}}";
      </script>
    {% elif pourcent_battery_recupere >= 40 and pourcent_battery_recupere <= 80 %}
      <script>
        var batteryImg = document.getElementById("battery-image");
        batteryImg.src = "{{url_for('static',filename='ressource/medium.png')}}";
      </script>
    {% else %}
      <script>
        var batteryImg = document.getElementById("battery-image");
        batteryImg.src = "{{url_for('static',filename='ressource/low.png')}}";
      </script>
    {% endif %}
    {% endif %}

</div>

website/templates/partials/_navbar.html
<script>
    var set_view = function(show_lr){
        show_lr = "" + show_lr;
        var etatContainer = document.getElementById('etatContainer');
        var boolToggle = document.getElementById('boolToggle');
        let boolValue = show_lr.toLowerCase() === 'true' || show_lr.toLowerCase() === '1';
        etatContainer.innerHTML = boolValue;
        // boolToggle.value is the parameter used when sending a request to change resolution
        // so it's negative to the check state
        if (boolValue) {
            boolToggle.checked = "";
            {#document.getElementsByClassName('bool-label')[0].innerHTML = "Passer en haute qualité d'image";#}
        } else {
            {#boolToggle.value = "false"#}
            boolToggle.checked = "checked";
            {#document.getElementsByClassName('bool-label')[0].innerHTML = "Passer en basse qualité d'image";#}
        }
    }

    var update_view = function(responseText){
        set_view(JSON.parse(responseText)['lr']);
    }

    var get_img_res = function() {
        var xhttp = new XMLHttpRequest();
        xhttp.onload = function() {
            if (this.status == 200) {
                update_view(this.responseText);
            } else {
                console.error('Erreur lors de la requête AJAX');
            }
        };
        xhttp.onerror = (e) => {
            console.error(xhttp.statusText);
        };
        xhttp.open("GET", "{{ url_for('api.image_quality') }}", true);
        xhttp.send();
    };

    var set_img_res = function(){
        var xhttp = new XMLHttpRequest();
        xhttp.onreadystatechange = function() {
            if (this.readyState === XMLHttpRequest.DONE) {
              if (this.status === 200) {
                location.reload();
              } else {
                console.error('Erreur lors de la requête AJAX');
              }
            }
        };
        var new_value;
        if (document.getElementById('boolToggle').checked){
            new_value = "False";
        } else {
            new_value = "True";
        }
        xhttp.open('GET', '{{ url_for('api.image_quality') }}?lr=' + new_value);
        xhttp.send();
    };

    //
    const body = document.querySelector('body');
    body.onload = function (){
        get_img_res();
        document.getElementById('boolToggle').addEventListener('change', function() {
            set_img_res();
        });
    }
    //



</script>
<div id="etatContainer"></div>
<nav class="sigle">
  <img src="{{url_for('static', filename='ressource/logo_remov.png')}}">
  <h1>Low-Tech Lab de Brest</h1>
  <div style="display: flex">
      <div class="bool-button">
        <input type="checkbox" id="boolToggle" class="bool-toggle" />
        <label for="boolToggle" class="bool-label"></label>
      </div>
      <div class="dropdown">
          <select id="colorFilterSelect" class="select-dropdown">
            <option>Vision couleur</option>
            <option>Protanopie</option>
            <option>Protanomalie</option>
            <option>Deutéranopie</option>
            <option>Deutéranomalie</option>
            <option>Tritanopie</option>
            <option>Tritanomalie</option>
            <option>Achromatomalie</option>
          </select>
          <span class="dropdown-arrow"></span>
      </div>
  </div>

</nav>

<div class="menu">
    <a href="{{ url_for('main.home') }}"  {% if active == 'home' %} class="active" {% endif %}>Accueil</a>
    <a href="{{ url_for('blog.display') }}" {% if active == 'blog' %} class="active" {% endif %}>Articles</a>
    <a href="#">Agenda</a>
    <a href="#">Projets</a>
    <a href="{{ url_for('main.a_propos') }}" {% if active == 'a_propos' %} class="active" {% endif %}>C'est quoi le Low-tech ?</a>
    <a href="{{ url_for('dashboard.display') }}" {% if active == 'dashboard' %} class="active" {% endif %}>Serveur solaire</a>
</div>

{% for message in get_flashed_messages() %}
<div class="flash alert alert-danger">{{ message }}</div>
{% endfor %}


<svg style="display: none">
    <defs>
    <filter id="protanopiaColourMatrix"> <!--id du filtre-->
    <feColorMatrix
        type="matrix"
        values=".56667 .43333 0      0 0
                .55833 .44167 0      0 0
                0      .24167 .75833 0 0
                0      0      0      1 0" /> <!--matrice de couleur relative à la protanopia (nom anglais)-->
    </filter>
    <filter id="protanomalyColourMatrix">
        <feColorMatrix
        type="matrix"
        values=".81667 .18333 0    0 0
                .33333 .66667 0    0 0
                0      .125   .875 0 0
                0      0      0    1 0" />
    </filter>
    <filter id="deuteranopiaColourMatrix"> <!--id du filtre-->
    <feColorMatrix
        type="matrix"
        values=".625 .375 0  0 0
                .7   .3   0  0 0
                0    .3   .7 0 0
                0    0    0  1 0" /> <!--matrice de couleur relative à la deuteranopia (nom anglais)-->
    </filter>
    <filter id="deutranomalyColourMatrix"> <!--id du filtre-->
    <feColorMatrix
        type="matrix"
        values=".8     .2     0      0 0
                .25833 .74167 0      0 0
                0      .14167 .85833 0 0
                0      0      0      1 0" /> <!--matrice de couleur relative à la deutranomaly (nom anglais)-->
    </filter>
    <filter id="tritanopiaColourMatrix"> <!--id du filtre-->
    <feColorMatrix
        type="matrix"
        values=".95 .5     0      0 0
                0   .43333 .56667 0 0
                0   .475   .525   0 0
                0   0      0      1 0" /> <!--matrice de couleur relative à la tritanopia (nom anglais)-->
    </filter>
    <filter id="tritanomalyColourMatrix"> <!--id du filtre-->
    <feColorMatrix
        type="matrix"
        values=".96667 .3333  0      0 0
                0      .73333 .26667 0 0
                0      .18333 .81667 0 0
                0      0      0      1 0" /> <!--matrice de couleur relative à la tritanomaly (nom anglais)-->
    </filter>
    <filter id="achromatomalyColourMatrix"> <!--id du filtre-->
        <feColorMatrix
            type="matrix"
            values=".618 .32  .62  0 0
                    .163 .775 .62  0 0
                    .163 .320 .516 0 0
                    0    0    0    1 0" /> <!--matrice de couleur relative à l'achromatomaly (nom anglais)-->
    </filter>
    </defs>
</svg>

<script>
var CONTENU = document.body;
var select = document.getElementById("colorFilterSelect"); /* REGARDE CE QUI EST SELECTIONNEE DANS LE BOUTTON colorFilterSelec */
select.addEventListener("change", function() { /* ECOUTE S'IL Y A DU CHANGEMENT DANS select SI OUI IL EFFECTUE FONCTION DEFINIE EN DESSOUS */
  if (select.value === "Protanopie") {
    CONTENU.style.filter = "url(#protanopiaColourMatrix)";
  } else if (select.value === "Protanomalie") {
    CONTENU.style.filter = "url(#protanomalyColourMatrix)";
  } else if (select.value === "Deutéranopie") {
    CONTENU.style.filter = "url(#deuteranopiaColourMatrix)";
  } else if (select.value === "Deutéranomalie") {               /* TEST DE LA VALEUR DE select */
    CONTENU.style.filter = "url(#deutranomalyColourMatrix)";  /* APPLIQUE AUX div d'ID "CONTENU" LE FILTRE D'URL DONNEE */
  } else if (select.value === "Tritanopie") {
    CONTENU.style.filter = "url(#tritanopiaColourMatrix)";
  } else if (select.value === "Tritanomalie") {
    CONTENU.style.filter = "url(#tritanomalyColourMatrix)";
  } else if (select.value === "Achromatopsie") {
    CONTENU.style.filter = "url(#achromatopsiaColourMatrix)";
  } else {
    CONTENU.style.filter = "none";
  }
});
</script>

website/templates/partials/_pastille_site.html
<div class="bottomright">
  <img id="battery-image" src="{{
    url_for('static', filename='/../ressource/low.png')
  }}" width="30" height="30">
</div>

{% if pourcent_battery_recupere is not none %}
{% if pourcent_battery_recupere >= 80 %}
  <script>
    var batteryImg = document.getElementById("battery-image");
    batteryImg.src = "{{url_for('static',filename='/../ressource/high.png')}}";
  </script>
{% elif pourcent_battery_recupere >= 40 and pourcent_battery_recupere <= 80 %}
  <script>
    var batteryImg = document.getElementById("battery-image");
    batteryImg.src = "{{url_for('static',filename='/../ressource/medium.png')}}";
  </script>
{% else %}
  <script>
    var batteryImg = document.getElementById("battery-image");
    batteryImg.src = "{{url_for('static',filename='/../ressource/low.png')}}";
  </script>
{% endif %}
{% endif %}